/** Países + código de discado, para el selector de teléfono y el de país del registro (server/auth.ts los combina/valida). */
export interface Country {
  name: string;
  dialCode: string;
  iso2: string;
}

export const COUNTRIES: Country[] = [
  { name: "Colombia", dialCode: "+57", iso2: "CO" },
  { name: "Venezuela", dialCode: "+58", iso2: "VE" },
  { name: "México", dialCode: "+52", iso2: "MX" },
  { name: "Argentina", dialCode: "+54", iso2: "AR" },
  { name: "Chile", dialCode: "+56", iso2: "CL" },
  { name: "Perú", dialCode: "+51", iso2: "PE" },
  { name: "Ecuador", dialCode: "+593", iso2: "EC" },
  { name: "Bolivia", dialCode: "+591", iso2: "BO" },
  { name: "Paraguay", dialCode: "+595", iso2: "PY" },
  { name: "Uruguay", dialCode: "+598", iso2: "UY" },
  { name: "Brasil", dialCode: "+55", iso2: "BR" },
  { name: "Panamá", dialCode: "+507", iso2: "PA" },
  { name: "Costa Rica", dialCode: "+506", iso2: "CR" },
  { name: "Nicaragua", dialCode: "+505", iso2: "NI" },
  { name: "Honduras", dialCode: "+504", iso2: "HN" },
  { name: "El Salvador", dialCode: "+503", iso2: "SV" },
  { name: "Guatemala", dialCode: "+502", iso2: "GT" },
  { name: "Belice", dialCode: "+501", iso2: "BZ" },
  { name: "Cuba", dialCode: "+53", iso2: "CU" },
  { name: "República Dominicana", dialCode: "+1", iso2: "DO" },
  { name: "Puerto Rico", dialCode: "+1", iso2: "PR" },
  { name: "España", dialCode: "+34", iso2: "ES" },
  { name: "Estados Unidos", dialCode: "+1", iso2: "US" },
  { name: "Canadá", dialCode: "+1", iso2: "CA" },
  { name: "Guyana", dialCode: "+592", iso2: "GY" },
  { name: "Surinam", dialCode: "+597", iso2: "SR" },
  { name: "Portugal", dialCode: "+351", iso2: "PT" },
  { name: "Francia", dialCode: "+33", iso2: "FR" },
  { name: "Italia", dialCode: "+39", iso2: "IT" },
  { name: "Alemania", dialCode: "+49", iso2: "DE" },
  { name: "Reino Unido", dialCode: "+44", iso2: "GB" },
  { name: "Países Bajos", dialCode: "+31", iso2: "NL" },
  { name: "Suiza", dialCode: "+41", iso2: "CH" },
  { name: "Bélgica", dialCode: "+32", iso2: "BE" },
  { name: "Suecia", dialCode: "+46", iso2: "SE" },
  { name: "Andorra", dialCode: "+376", iso2: "AD" },
  { name: "Australia", dialCode: "+61", iso2: "AU" },
  { name: "Nueva Zelanda", dialCode: "+64", iso2: "NZ" },
  { name: "Japón", dialCode: "+81", iso2: "JP" },
  { name: "China", dialCode: "+86", iso2: "CN" },
  { name: "Corea del Sur", dialCode: "+82", iso2: "KR" },
  { name: "India", dialCode: "+91", iso2: "IN" },
  { name: "Filipinas", dialCode: "+63", iso2: "PH" },
  { name: "Israel", dialCode: "+972", iso2: "IL" },
  { name: "Emiratos Árabes Unidos", dialCode: "+971", iso2: "AE" },
  { name: "Sudáfrica", dialCode: "+27", iso2: "ZA" },
  { name: "Marruecos", dialCode: "+212", iso2: "MA" },
  { name: "Otro país", dialCode: "+", iso2: "XX" },
];
